/* soapTMSServiceSoapProxy.h
   Generated by gSOAP 2.8.19 from d:\Structure\TMSServTemp\TmsServer.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapTMSServiceSoapProxy_H
#define soapTMSServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC TMSServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'TMSServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in d:\Structure\TMSServTemp\TmsServer.h (non-static)
	/// Constructor
	TMSServiceSoapProxy();
	/// Construct from another engine state
	TMSServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	TMSServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	TMSServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	TMSServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	TMSServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~TMSServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void TMSServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'loginUser' (returns error code or SOAP_OK)
	virtual	int loginUser(_ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse) { return this->loginUser(NULL, NULL, ns1__loginUser, ns1__loginUserResponse); }
	virtual	int loginUser(const char *endpoint, const char *soap_action, _ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse);

	/// Web service operation 'loginUserByByteArr' (returns error code or SOAP_OK)
	virtual	int loginUserByByteArr(_ns1__loginUserByByteArr *ns1__loginUserByByteArr, _ns1__loginUserByByteArrResponse &ns1__loginUserByByteArrResponse) { return this->loginUserByByteArr(NULL, NULL, ns1__loginUserByByteArr, ns1__loginUserByByteArrResponse); }
	virtual	int loginUserByByteArr(const char *endpoint, const char *soap_action, _ns1__loginUserByByteArr *ns1__loginUserByByteArr, _ns1__loginUserByByteArrResponse &ns1__loginUserByByteArrResponse);

	/// Web service operation 'logoutUser' (returns error code or SOAP_OK)
	virtual	int logoutUser(_ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse) { return this->logoutUser(NULL, NULL, ns1__logoutUser, ns1__logoutUserResponse); }
	virtual	int logoutUser(const char *endpoint, const char *soap_action, _ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse);

	/// Web service operation 'QueryObjects' (returns error code or SOAP_OK)
	virtual	int QueryObjects(_ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse) { return this->QueryObjects(NULL, NULL, ns1__QueryObjects, ns1__QueryObjectsResponse); }
	virtual	int QueryObjects(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse);

	/// Web service operation 'DownloadObjects' (returns error code or SOAP_OK)
	virtual	int DownloadObjects(_ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse) { return this->DownloadObjects(NULL, NULL, ns1__DownloadObjects, ns1__DownloadObjectsResponse); }
	virtual	int DownloadObjects(const char *endpoint, const char *soap_action, _ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse);

	/// Web service operation 'GetObjectsVersion' (returns error code or SOAP_OK)
	virtual	int GetObjectsVersion(_ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse) { return this->GetObjectsVersion(NULL, NULL, ns1__GetObjectsVersion, ns1__GetObjectsVersionResponse); }
	virtual	int GetObjectsVersion(const char *endpoint, const char *soap_action, _ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse);

	/// Web service operation 'GetTowerPartsLabelAndVersionSerial' (returns error code or SOAP_OK)
	virtual	int GetTowerPartsLabelAndVersionSerial(_ns1__GetTowerPartsLabelAndVersionSerial *ns1__GetTowerPartsLabelAndVersionSerial, _ns1__GetTowerPartsLabelAndVersionSerialResponse &ns1__GetTowerPartsLabelAndVersionSerialResponse) { return this->GetTowerPartsLabelAndVersionSerial(NULL, NULL, ns1__GetTowerPartsLabelAndVersionSerial, ns1__GetTowerPartsLabelAndVersionSerialResponse); }
	virtual	int GetTowerPartsLabelAndVersionSerial(const char *endpoint, const char *soap_action, _ns1__GetTowerPartsLabelAndVersionSerial *ns1__GetTowerPartsLabelAndVersionSerial, _ns1__GetTowerPartsLabelAndVersionSerialResponse &ns1__GetTowerPartsLabelAndVersionSerialResponse);

	/// Web service operation 'MatchTowerParts' (returns error code or SOAP_OK)
	virtual	int MatchTowerParts(_ns1__MatchTowerParts *ns1__MatchTowerParts, _ns1__MatchTowerPartsResponse &ns1__MatchTowerPartsResponse) { return this->MatchTowerParts(NULL, NULL, ns1__MatchTowerParts, ns1__MatchTowerPartsResponse); }
	virtual	int MatchTowerParts(const char *endpoint, const char *soap_action, _ns1__MatchTowerParts *ns1__MatchTowerParts, _ns1__MatchTowerPartsResponse &ns1__MatchTowerPartsResponse);

	/// Web service operation 'SaveOrUpdateObjects' (returns error code or SOAP_OK)
	virtual	int SaveOrUpdateObjects(_ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse) { return this->SaveOrUpdateObjects(NULL, NULL, ns1__SaveOrUpdateObjects, ns1__SaveOrUpdateObjectsResponse); }
	virtual	int SaveOrUpdateObjects(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse);

	/// Web service operation 'DeleteObject' (returns error code or SOAP_OK)
	virtual	int DeleteObject(_ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse) { return this->DeleteObject(NULL, NULL, ns1__DeleteObject, ns1__DeleteObjectResponse); }
	virtual	int DeleteObject(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse);

	/// Web service operation 'DownloadFileById' (returns error code or SOAP_OK)
	virtual	int DownloadFileById(_ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse) { return this->DownloadFileById(NULL, NULL, ns1__DownloadFileById, ns1__DownloadFileByIdResponse); }
	virtual	int DownloadFileById(const char *endpoint, const char *soap_action, _ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse);

	/// Web service operation 'UploadFileObject' (returns error code or SOAP_OK)
	virtual	int UploadFileObject(_ns1__UploadFileObject *ns1__UploadFileObject, _ns1__UploadFileObjectResponse &ns1__UploadFileObjectResponse) { return this->UploadFileObject(NULL, NULL, ns1__UploadFileObject, ns1__UploadFileObjectResponse); }
	virtual	int UploadFileObject(const char *endpoint, const char *soap_action, _ns1__UploadFileObject *ns1__UploadFileObject, _ns1__UploadFileObjectResponse &ns1__UploadFileObjectResponse);

	/// Web service operation 'FinalizeFileObjectData' (returns error code or SOAP_OK)
	virtual	int FinalizeFileObjectData(_ns1__FinalizeFileObjectData *ns1__FinalizeFileObjectData, _ns1__FinalizeFileObjectDataResponse &ns1__FinalizeFileObjectDataResponse) { return this->FinalizeFileObjectData(NULL, NULL, ns1__FinalizeFileObjectData, ns1__FinalizeFileObjectDataResponse); }
	virtual	int FinalizeFileObjectData(const char *endpoint, const char *soap_action, _ns1__FinalizeFileObjectData *ns1__FinalizeFileObjectData, _ns1__FinalizeFileObjectDataResponse &ns1__FinalizeFileObjectDataResponse);

	/// Web service operation 'OpenFileObjectDataProvider' (returns error code or SOAP_OK)
	virtual	int OpenFileObjectDataProvider(_ns1__OpenFileObjectDataProvider *ns1__OpenFileObjectDataProvider, _ns1__OpenFileObjectDataProviderResponse &ns1__OpenFileObjectDataProviderResponse) { return this->OpenFileObjectDataProvider(NULL, NULL, ns1__OpenFileObjectDataProvider, ns1__OpenFileObjectDataProviderResponse); }
	virtual	int OpenFileObjectDataProvider(const char *endpoint, const char *soap_action, _ns1__OpenFileObjectDataProvider *ns1__OpenFileObjectDataProvider, _ns1__OpenFileObjectDataProviderResponse &ns1__OpenFileObjectDataProviderResponse);

	/// Web service operation 'OpenTapModelDataProvider' (returns error code or SOAP_OK)
	virtual	int OpenTapModelDataProvider(_ns1__OpenTapModelDataProvider *ns1__OpenTapModelDataProvider, _ns1__OpenTapModelDataProviderResponse &ns1__OpenTapModelDataProviderResponse) { return this->OpenTapModelDataProvider(NULL, NULL, ns1__OpenTapModelDataProvider, ns1__OpenTapModelDataProviderResponse); }
	virtual	int OpenTapModelDataProvider(const char *endpoint, const char *soap_action, _ns1__OpenTapModelDataProvider *ns1__OpenTapModelDataProvider, _ns1__OpenTapModelDataProviderResponse &ns1__OpenTapModelDataProviderResponse);

	/// Web service operation 'OpenServerObjectDataProvider' (returns error code or SOAP_OK)
	virtual	int OpenServerObjectDataProvider(_ns1__OpenServerObjectDataProvider *ns1__OpenServerObjectDataProvider, _ns1__OpenServerObjectDataProviderResponse &ns1__OpenServerObjectDataProviderResponse) { return this->OpenServerObjectDataProvider(NULL, NULL, ns1__OpenServerObjectDataProvider, ns1__OpenServerObjectDataProviderResponse); }
	virtual	int OpenServerObjectDataProvider(const char *endpoint, const char *soap_action, _ns1__OpenServerObjectDataProvider *ns1__OpenServerObjectDataProvider, _ns1__OpenServerObjectDataProviderResponse &ns1__OpenServerObjectDataProviderResponse);

	/// Web service operation 'DownloadFileObject' (returns error code or SOAP_OK)
	virtual	int DownloadFileObject(_ns1__DownloadFileObject *ns1__DownloadFileObject, _ns1__DownloadFileObjectResponse &ns1__DownloadFileObjectResponse) { return this->DownloadFileObject(NULL, NULL, ns1__DownloadFileObject, ns1__DownloadFileObjectResponse); }
	virtual	int DownloadFileObject(const char *endpoint, const char *soap_action, _ns1__DownloadFileObject *ns1__DownloadFileObject, _ns1__DownloadFileObjectResponse &ns1__DownloadFileObjectResponse);

	/// Web service operation 'CloseFileObjectDataProvider' (returns error code or SOAP_OK)
	virtual	int CloseFileObjectDataProvider(_ns1__CloseFileObjectDataProvider *ns1__CloseFileObjectDataProvider, _ns1__CloseFileObjectDataProviderResponse &ns1__CloseFileObjectDataProviderResponse) { return this->CloseFileObjectDataProvider(NULL, NULL, ns1__CloseFileObjectDataProvider, ns1__CloseFileObjectDataProviderResponse); }
	virtual	int CloseFileObjectDataProvider(const char *endpoint, const char *soap_action, _ns1__CloseFileObjectDataProvider *ns1__CloseFileObjectDataProvider, _ns1__CloseFileObjectDataProviderResponse &ns1__CloseFileObjectDataProviderResponse);

	/// Web service operation 'loginUser' (returns error code or SOAP_OK)
	virtual	int loginUser_(_ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse) { return this->loginUser_(NULL, NULL, ns1__loginUser, ns1__loginUserResponse); }
	virtual	int loginUser_(const char *endpoint, const char *soap_action, _ns1__loginUser *ns1__loginUser, _ns1__loginUserResponse &ns1__loginUserResponse);

	/// Web service operation 'loginUserByByteArr' (returns error code or SOAP_OK)
	virtual	int loginUserByByteArr_(_ns1__loginUserByByteArr *ns1__loginUserByByteArr, _ns1__loginUserByByteArrResponse &ns1__loginUserByByteArrResponse) { return this->loginUserByByteArr_(NULL, NULL, ns1__loginUserByByteArr, ns1__loginUserByByteArrResponse); }
	virtual	int loginUserByByteArr_(const char *endpoint, const char *soap_action, _ns1__loginUserByByteArr *ns1__loginUserByByteArr, _ns1__loginUserByByteArrResponse &ns1__loginUserByByteArrResponse);

	/// Web service operation 'logoutUser' (returns error code or SOAP_OK)
	virtual	int logoutUser_(_ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse) { return this->logoutUser_(NULL, NULL, ns1__logoutUser, ns1__logoutUserResponse); }
	virtual	int logoutUser_(const char *endpoint, const char *soap_action, _ns1__logoutUser *ns1__logoutUser, _ns1__logoutUserResponse &ns1__logoutUserResponse);

	/// Web service operation 'QueryObjects' (returns error code or SOAP_OK)
	virtual	int QueryObjects_(_ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse) { return this->QueryObjects_(NULL, NULL, ns1__QueryObjects, ns1__QueryObjectsResponse); }
	virtual	int QueryObjects_(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse);

	/// Web service operation 'DownloadObjects' (returns error code or SOAP_OK)
	virtual	int DownloadObjects_(_ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse) { return this->DownloadObjects_(NULL, NULL, ns1__DownloadObjects, ns1__DownloadObjectsResponse); }
	virtual	int DownloadObjects_(const char *endpoint, const char *soap_action, _ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse);

	/// Web service operation 'GetObjectsVersion' (returns error code or SOAP_OK)
	virtual	int GetObjectsVersion_(_ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse) { return this->GetObjectsVersion_(NULL, NULL, ns1__GetObjectsVersion, ns1__GetObjectsVersionResponse); }
	virtual	int GetObjectsVersion_(const char *endpoint, const char *soap_action, _ns1__GetObjectsVersion *ns1__GetObjectsVersion, _ns1__GetObjectsVersionResponse &ns1__GetObjectsVersionResponse);

	/// Web service operation 'GetTowerPartsLabelAndVersionSerial' (returns error code or SOAP_OK)
	virtual	int GetTowerPartsLabelAndVersionSerial_(_ns1__GetTowerPartsLabelAndVersionSerial *ns1__GetTowerPartsLabelAndVersionSerial, _ns1__GetTowerPartsLabelAndVersionSerialResponse &ns1__GetTowerPartsLabelAndVersionSerialResponse) { return this->GetTowerPartsLabelAndVersionSerial_(NULL, NULL, ns1__GetTowerPartsLabelAndVersionSerial, ns1__GetTowerPartsLabelAndVersionSerialResponse); }
	virtual	int GetTowerPartsLabelAndVersionSerial_(const char *endpoint, const char *soap_action, _ns1__GetTowerPartsLabelAndVersionSerial *ns1__GetTowerPartsLabelAndVersionSerial, _ns1__GetTowerPartsLabelAndVersionSerialResponse &ns1__GetTowerPartsLabelAndVersionSerialResponse);

	/// Web service operation 'MatchTowerParts' (returns error code or SOAP_OK)
	virtual	int MatchTowerParts_(_ns1__MatchTowerParts *ns1__MatchTowerParts, _ns1__MatchTowerPartsResponse &ns1__MatchTowerPartsResponse) { return this->MatchTowerParts_(NULL, NULL, ns1__MatchTowerParts, ns1__MatchTowerPartsResponse); }
	virtual	int MatchTowerParts_(const char *endpoint, const char *soap_action, _ns1__MatchTowerParts *ns1__MatchTowerParts, _ns1__MatchTowerPartsResponse &ns1__MatchTowerPartsResponse);

	/// Web service operation 'SaveOrUpdateObjects' (returns error code or SOAP_OK)
	virtual	int SaveOrUpdateObjects_(_ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse) { return this->SaveOrUpdateObjects_(NULL, NULL, ns1__SaveOrUpdateObjects, ns1__SaveOrUpdateObjectsResponse); }
	virtual	int SaveOrUpdateObjects_(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse);

	/// Web service operation 'DeleteObject' (returns error code or SOAP_OK)
	virtual	int DeleteObject_(_ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse) { return this->DeleteObject_(NULL, NULL, ns1__DeleteObject, ns1__DeleteObjectResponse); }
	virtual	int DeleteObject_(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse &ns1__DeleteObjectResponse);

	/// Web service operation 'DownloadFileById' (returns error code or SOAP_OK)
	virtual	int DownloadFileById_(_ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse) { return this->DownloadFileById_(NULL, NULL, ns1__DownloadFileById, ns1__DownloadFileByIdResponse); }
	virtual	int DownloadFileById_(const char *endpoint, const char *soap_action, _ns1__DownloadFileById *ns1__DownloadFileById, _ns1__DownloadFileByIdResponse &ns1__DownloadFileByIdResponse);

	/// Web service operation 'UploadFileObject' (returns error code or SOAP_OK)
	virtual	int UploadFileObject_(_ns1__UploadFileObject *ns1__UploadFileObject, _ns1__UploadFileObjectResponse &ns1__UploadFileObjectResponse) { return this->UploadFileObject_(NULL, NULL, ns1__UploadFileObject, ns1__UploadFileObjectResponse); }
	virtual	int UploadFileObject_(const char *endpoint, const char *soap_action, _ns1__UploadFileObject *ns1__UploadFileObject, _ns1__UploadFileObjectResponse &ns1__UploadFileObjectResponse);

	/// Web service operation 'FinalizeFileObjectData' (returns error code or SOAP_OK)
	virtual	int FinalizeFileObjectData_(_ns1__FinalizeFileObjectData *ns1__FinalizeFileObjectData, _ns1__FinalizeFileObjectDataResponse &ns1__FinalizeFileObjectDataResponse) { return this->FinalizeFileObjectData_(NULL, NULL, ns1__FinalizeFileObjectData, ns1__FinalizeFileObjectDataResponse); }
	virtual	int FinalizeFileObjectData_(const char *endpoint, const char *soap_action, _ns1__FinalizeFileObjectData *ns1__FinalizeFileObjectData, _ns1__FinalizeFileObjectDataResponse &ns1__FinalizeFileObjectDataResponse);

	/// Web service operation 'OpenFileObjectDataProvider' (returns error code or SOAP_OK)
	virtual	int OpenFileObjectDataProvider_(_ns1__OpenFileObjectDataProvider *ns1__OpenFileObjectDataProvider, _ns1__OpenFileObjectDataProviderResponse &ns1__OpenFileObjectDataProviderResponse) { return this->OpenFileObjectDataProvider_(NULL, NULL, ns1__OpenFileObjectDataProvider, ns1__OpenFileObjectDataProviderResponse); }
	virtual	int OpenFileObjectDataProvider_(const char *endpoint, const char *soap_action, _ns1__OpenFileObjectDataProvider *ns1__OpenFileObjectDataProvider, _ns1__OpenFileObjectDataProviderResponse &ns1__OpenFileObjectDataProviderResponse);

	/// Web service operation 'OpenTapModelDataProvider' (returns error code or SOAP_OK)
	virtual	int OpenTapModelDataProvider_(_ns1__OpenTapModelDataProvider *ns1__OpenTapModelDataProvider, _ns1__OpenTapModelDataProviderResponse &ns1__OpenTapModelDataProviderResponse) { return this->OpenTapModelDataProvider_(NULL, NULL, ns1__OpenTapModelDataProvider, ns1__OpenTapModelDataProviderResponse); }
	virtual	int OpenTapModelDataProvider_(const char *endpoint, const char *soap_action, _ns1__OpenTapModelDataProvider *ns1__OpenTapModelDataProvider, _ns1__OpenTapModelDataProviderResponse &ns1__OpenTapModelDataProviderResponse);

	/// Web service operation 'OpenServerObjectDataProvider' (returns error code or SOAP_OK)
	virtual	int OpenServerObjectDataProvider_(_ns1__OpenServerObjectDataProvider *ns1__OpenServerObjectDataProvider, _ns1__OpenServerObjectDataProviderResponse &ns1__OpenServerObjectDataProviderResponse) { return this->OpenServerObjectDataProvider_(NULL, NULL, ns1__OpenServerObjectDataProvider, ns1__OpenServerObjectDataProviderResponse); }
	virtual	int OpenServerObjectDataProvider_(const char *endpoint, const char *soap_action, _ns1__OpenServerObjectDataProvider *ns1__OpenServerObjectDataProvider, _ns1__OpenServerObjectDataProviderResponse &ns1__OpenServerObjectDataProviderResponse);

	/// Web service operation 'DownloadFileObject' (returns error code or SOAP_OK)
	virtual	int DownloadFileObject_(_ns1__DownloadFileObject *ns1__DownloadFileObject, _ns1__DownloadFileObjectResponse &ns1__DownloadFileObjectResponse) { return this->DownloadFileObject_(NULL, NULL, ns1__DownloadFileObject, ns1__DownloadFileObjectResponse); }
	virtual	int DownloadFileObject_(const char *endpoint, const char *soap_action, _ns1__DownloadFileObject *ns1__DownloadFileObject, _ns1__DownloadFileObjectResponse &ns1__DownloadFileObjectResponse);

	/// Web service operation 'CloseFileObjectDataProvider' (returns error code or SOAP_OK)
	virtual	int CloseFileObjectDataProvider_(_ns1__CloseFileObjectDataProvider *ns1__CloseFileObjectDataProvider, _ns1__CloseFileObjectDataProviderResponse &ns1__CloseFileObjectDataProviderResponse) { return this->CloseFileObjectDataProvider_(NULL, NULL, ns1__CloseFileObjectDataProvider, ns1__CloseFileObjectDataProviderResponse); }
	virtual	int CloseFileObjectDataProvider_(const char *endpoint, const char *soap_action, _ns1__CloseFileObjectDataProvider *ns1__CloseFileObjectDataProvider, _ns1__CloseFileObjectDataProviderResponse &ns1__CloseFileObjectDataProviderResponse);
};
#endif
