/* soapVersionServiceSoapProxy.h
   Generated by gSOAP 2.8.19 from D:\Structure\VersionServTemp\VerServer.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapVersionServiceSoapProxy_H
#define soapVersionServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC VersionServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'VersionServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in D:\Structure\VersionServTemp\VerServer.h (non-static)
	/// Constructor
	VersionServiceSoapProxy();
	/// Construct from another engine state
	VersionServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	VersionServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	VersionServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	VersionServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	VersionServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~VersionServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void VersionServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) { return this->Login(NULL, NULL, ns1__Login, ns1__LoginResponse); }
	virtual	int Login(const char *endpoint, const char *soap_action, _ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse);

	/// Web service operation 'LoginByByteArr' (returns error code or SOAP_OK)
	virtual	int LoginByByteArr(_ns1__LoginByByteArr *ns1__LoginByByteArr, _ns1__LoginByByteArrResponse &ns1__LoginByByteArrResponse){ return this->LoginByByteArr(NULL, NULL, ns1__LoginByByteArr, ns1__LoginByByteArrResponse); }
	virtual	int LoginByByteArr(const char *endpoint, const char *soap_action, _ns1__LoginByByteArr *ns1__LoginByByteArr, _ns1__LoginByByteArrResponse &ns1__LoginByByteArrResponse);

	/// Web service operation 'GetUpdateVerByCurVer' (returns error code or SOAP_OK)
	virtual	int GetUpdateVerByCurVer(_ns1__GetUpdateVerByCurVer *ns1__GetUpdateVerByCurVer, _ns1__GetUpdateVerByCurVerResponse &ns1__GetUpdateVerByCurVerResponse) { return this->GetUpdateVerByCurVer(NULL, NULL, ns1__GetUpdateVerByCurVer, ns1__GetUpdateVerByCurVerResponse); }
	virtual	int GetUpdateVerByCurVer(const char *endpoint, const char *soap_action, _ns1__GetUpdateVerByCurVer *ns1__GetUpdateVerByCurVer, _ns1__GetUpdateVerByCurVerResponse &ns1__GetUpdateVerByCurVerResponse);

	/// Web service operation 'SetRevisionReadFlag' (returns error code or SOAP_OK)
	virtual	int SetRevisionReadFlag(_ns1__SetRevisionReadFlag *ns1__SetRevisionReadFlag, _ns1__SetRevisionReadFlagResponse &ns1__SetRevisionReadFlagResponse) { return this->SetRevisionReadFlag(NULL, NULL, ns1__SetRevisionReadFlag, ns1__SetRevisionReadFlagResponse); }
	virtual	int SetRevisionReadFlag(const char *endpoint, const char *soap_action, _ns1__SetRevisionReadFlag *ns1__SetRevisionReadFlag, _ns1__SetRevisionReadFlagResponse &ns1__SetRevisionReadFlagResponse);

	/// Web service operation 'CompareVersion' (returns error code or SOAP_OK)
	virtual	int CompareVersion(_ns1__CompareVersion *ns1__CompareVersion, _ns1__CompareVersionResponse &ns1__CompareVersionResponse) { return this->CompareVersion(NULL, NULL, ns1__CompareVersion, ns1__CompareVersionResponse); }
	virtual	int CompareVersion(const char *endpoint, const char *soap_action, _ns1__CompareVersion *ns1__CompareVersion, _ns1__CompareVersionResponse &ns1__CompareVersionResponse);

	/// Web service operation 'GetVersionReleaseNotes' (returns error code or SOAP_OK)
	virtual	int GetVersionReleaseNotes(_ns1__GetVersionReleaseNotes *ns1__GetVersionReleaseNotes, _ns1__GetVersionReleaseNotesResponse &ns1__GetVersionReleaseNotesResponse) { return this->GetVersionReleaseNotes(NULL, NULL, ns1__GetVersionReleaseNotes, ns1__GetVersionReleaseNotesResponse); }
	virtual	int GetVersionReleaseNotes(const char *endpoint, const char *soap_action, _ns1__GetVersionReleaseNotes *ns1__GetVersionReleaseNotes, _ns1__GetVersionReleaseNotesResponse &ns1__GetVersionReleaseNotesResponse);

	/// Web service operation 'GetDogAccessHistory' (returns error code or SOAP_OK)
	virtual	int GetDogAccessHistory(_ns1__GetDogAccessHistory *ns1__GetDogAccessHistory, _ns1__GetDogAccessHistoryResponse &ns1__GetDogAccessHistoryResponse) { return this->GetDogAccessHistory(NULL, NULL, ns1__GetDogAccessHistory, ns1__GetDogAccessHistoryResponse); }
	virtual	int GetDogAccessHistory(const char *endpoint, const char *soap_action, _ns1__GetDogAccessHistory *ns1__GetDogAccessHistory, _ns1__GetDogAccessHistoryResponse &ns1__GetDogAccessHistoryResponse);

	/// Web service operation 'QueryDownLoadItemArrByProductId' (returns error code or SOAP_OK)
	virtual	int QueryDownLoadItemArrByProductId(_ns1__QueryDownLoadItemArrByProductId *ns1__QueryDownLoadItemArrByProductId, _ns1__QueryDownLoadItemArrByProductIdResponse &ns1__QueryDownLoadItemArrByProductIdResponse) { return this->QueryDownLoadItemArrByProductId(NULL, NULL, ns1__QueryDownLoadItemArrByProductId, ns1__QueryDownLoadItemArrByProductIdResponse); }
	virtual	int QueryDownLoadItemArrByProductId(const char *endpoint, const char *soap_action, _ns1__QueryDownLoadItemArrByProductId *ns1__QueryDownLoadItemArrByProductId, _ns1__QueryDownLoadItemArrByProductIdResponse &ns1__QueryDownLoadItemArrByProductIdResponse);

	/// Web service operation 'GetFileHeader' (returns error code or SOAP_OK)
	virtual	int GetFileHeader(_ns1__GetFileHeader *ns1__GetFileHeader, _ns1__GetFileHeaderResponse &ns1__GetFileHeaderResponse) { return this->GetFileHeader(NULL, NULL, ns1__GetFileHeader, ns1__GetFileHeaderResponse); }
	virtual	int GetFileHeader(const char *endpoint, const char *soap_action, _ns1__GetFileHeader *ns1__GetFileHeader, _ns1__GetFileHeaderResponse &ns1__GetFileHeaderResponse);

	/// Web service operation 'QueryObjects' (returns error code or SOAP_OK)
	virtual	int QueryObjects(_ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse) { return this->QueryObjects(NULL, NULL, ns1__QueryObjects, ns1__QueryObjectsResponse); }
	virtual	int QueryObjects(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse);

	/// Web service operation 'DownloadObjects' (returns error code or SOAP_OK)
	virtual	int DownloadObjects(_ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse) { return this->DownloadObjects(NULL, NULL, ns1__DownloadObjects, ns1__DownloadObjectsResponse); }
	virtual	int DownloadObjects(const char *endpoint, const char *soap_action, _ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse);

	/// Web service operation 'SaveOrUpdateObjects' (returns error code or SOAP_OK)
	virtual	int SaveOrUpdateObjects(_ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse) { return this->SaveOrUpdateObjects(NULL, NULL, ns1__SaveOrUpdateObjects, ns1__SaveOrUpdateObjectsResponse); }
	virtual	int SaveOrUpdateObjects(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse);

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login_(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) { return this->Login_(NULL, NULL, ns1__Login, ns1__LoginResponse); }
	virtual	int Login_(const char *endpoint, const char *soap_action, _ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse);

	/// Web service operation 'LoginByByteArr' (returns error code or SOAP_OK)
	virtual	int LoginByByteArr_(_ns1__LoginByByteArr *ns1__LoginByByteArr, _ns1__LoginByByteArrResponse &ns1__LoginByByteArrResponse) { return this->LoginByByteArr_(NULL, NULL, ns1__LoginByByteArr, ns1__LoginByByteArrResponse); }
	virtual	int LoginByByteArr_(const char *endpoint, const char *soap_action, _ns1__LoginByByteArr *ns1__LoginByByteArr, _ns1__LoginByByteArrResponse &ns1__LoginByByteArrResponse);

	/// Web service operation 'GetUpdateVerByCurVer' (returns error code or SOAP_OK)
	virtual	int GetUpdateVerByCurVer_(_ns1__GetUpdateVerByCurVer *ns1__GetUpdateVerByCurVer, _ns1__GetUpdateVerByCurVerResponse &ns1__GetUpdateVerByCurVerResponse) { return this->GetUpdateVerByCurVer_(NULL, NULL, ns1__GetUpdateVerByCurVer, ns1__GetUpdateVerByCurVerResponse); }
	virtual	int GetUpdateVerByCurVer_(const char *endpoint, const char *soap_action, _ns1__GetUpdateVerByCurVer *ns1__GetUpdateVerByCurVer, _ns1__GetUpdateVerByCurVerResponse &ns1__GetUpdateVerByCurVerResponse);

	/// Web service operation 'SetRevisionReadFlag' (returns error code or SOAP_OK)
	virtual	int SetRevisionReadFlag_(_ns1__SetRevisionReadFlag *ns1__SetRevisionReadFlag, _ns1__SetRevisionReadFlagResponse &ns1__SetRevisionReadFlagResponse) { return this->SetRevisionReadFlag_(NULL, NULL, ns1__SetRevisionReadFlag, ns1__SetRevisionReadFlagResponse); }
	virtual	int SetRevisionReadFlag_(const char *endpoint, const char *soap_action, _ns1__SetRevisionReadFlag *ns1__SetRevisionReadFlag, _ns1__SetRevisionReadFlagResponse &ns1__SetRevisionReadFlagResponse);

	/// Web service operation 'CompareVersion' (returns error code or SOAP_OK)
	virtual	int CompareVersion_(_ns1__CompareVersion *ns1__CompareVersion, _ns1__CompareVersionResponse &ns1__CompareVersionResponse) { return this->CompareVersion_(NULL, NULL, ns1__CompareVersion, ns1__CompareVersionResponse); }
	virtual	int CompareVersion_(const char *endpoint, const char *soap_action, _ns1__CompareVersion *ns1__CompareVersion, _ns1__CompareVersionResponse &ns1__CompareVersionResponse);

	/// Web service operation 'GetVersionReleaseNotes' (returns error code or SOAP_OK)
	virtual	int GetVersionReleaseNotes_(_ns1__GetVersionReleaseNotes *ns1__GetVersionReleaseNotes, _ns1__GetVersionReleaseNotesResponse &ns1__GetVersionReleaseNotesResponse) { return this->GetVersionReleaseNotes_(NULL, NULL, ns1__GetVersionReleaseNotes, ns1__GetVersionReleaseNotesResponse); }
	virtual	int GetVersionReleaseNotes_(const char *endpoint, const char *soap_action, _ns1__GetVersionReleaseNotes *ns1__GetVersionReleaseNotes, _ns1__GetVersionReleaseNotesResponse &ns1__GetVersionReleaseNotesResponse);

	/// Web service operation 'GetDogAccessHistory' (returns error code or SOAP_OK)
	virtual	int GetDogAccessHistory_(_ns1__GetDogAccessHistory *ns1__GetDogAccessHistory, _ns1__GetDogAccessHistoryResponse &ns1__GetDogAccessHistoryResponse) { return this->GetDogAccessHistory_(NULL, NULL, ns1__GetDogAccessHistory, ns1__GetDogAccessHistoryResponse); }
	virtual	int GetDogAccessHistory_(const char *endpoint, const char *soap_action, _ns1__GetDogAccessHistory *ns1__GetDogAccessHistory, _ns1__GetDogAccessHistoryResponse &ns1__GetDogAccessHistoryResponse);

	/// Web service operation 'QueryDownLoadItemArrByProductId' (returns error code or SOAP_OK)
	virtual	int QueryDownLoadItemArrByProductId_(_ns1__QueryDownLoadItemArrByProductId *ns1__QueryDownLoadItemArrByProductId, _ns1__QueryDownLoadItemArrByProductIdResponse &ns1__QueryDownLoadItemArrByProductIdResponse) { return this->QueryDownLoadItemArrByProductId_(NULL, NULL, ns1__QueryDownLoadItemArrByProductId, ns1__QueryDownLoadItemArrByProductIdResponse); }
	virtual	int QueryDownLoadItemArrByProductId_(const char *endpoint, const char *soap_action, _ns1__QueryDownLoadItemArrByProductId *ns1__QueryDownLoadItemArrByProductId, _ns1__QueryDownLoadItemArrByProductIdResponse &ns1__QueryDownLoadItemArrByProductIdResponse);

	/// Web service operation 'GetFileHeader' (returns error code or SOAP_OK)
	virtual	int GetFileHeader_(_ns1__GetFileHeader *ns1__GetFileHeader, _ns1__GetFileHeaderResponse &ns1__GetFileHeaderResponse) { return this->GetFileHeader_(NULL, NULL, ns1__GetFileHeader, ns1__GetFileHeaderResponse); }
	virtual	int GetFileHeader_(const char *endpoint, const char *soap_action, _ns1__GetFileHeader *ns1__GetFileHeader, _ns1__GetFileHeaderResponse &ns1__GetFileHeaderResponse);

	/// Web service operation 'QueryObjects' (returns error code or SOAP_OK)
	virtual	int QueryObjects_(_ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse) { return this->QueryObjects_(NULL, NULL, ns1__QueryObjects, ns1__QueryObjectsResponse); }
	virtual	int QueryObjects_(const char *endpoint, const char *soap_action, _ns1__QueryObjects *ns1__QueryObjects, _ns1__QueryObjectsResponse &ns1__QueryObjectsResponse);

	/// Web service operation 'DownloadObjects' (returns error code or SOAP_OK)
	virtual	int DownloadObjects_(_ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse) { return this->DownloadObjects_(NULL, NULL, ns1__DownloadObjects, ns1__DownloadObjectsResponse); }
	virtual	int DownloadObjects_(const char *endpoint, const char *soap_action, _ns1__DownloadObjects *ns1__DownloadObjects, _ns1__DownloadObjectsResponse &ns1__DownloadObjectsResponse);

	/// Web service operation 'SaveOrUpdateObjects' (returns error code or SOAP_OK)
	virtual	int SaveOrUpdateObjects_(_ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse) { return this->SaveOrUpdateObjects_(NULL, NULL, ns1__SaveOrUpdateObjects, ns1__SaveOrUpdateObjectsResponse); }
	virtual	int SaveOrUpdateObjects_(const char *endpoint, const char *soap_action, _ns1__SaveOrUpdateObjects *ns1__SaveOrUpdateObjects, _ns1__SaveOrUpdateObjectsResponse &ns1__SaveOrUpdateObjectsResponse);
};
#endif
